import { useState, useEffect } from 'react'
import { Heart, Eye, ShoppingCart, CreditCard, MapPin, Home, TrendingUp, FileText, Zap } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { useFavorites } from '../context/FavoritesContext'
import PaymentGateway from '../components/PaymentGateway'
import ReportGenerator from '../components/ReportGenerator'

const BuyerDashboard = () => {
  const { user } = useAuth()
  const { favorites } = useFavorites()
  const [recentViews, setRecentViews] = useState([])
  const [purchases, setPurchases] = useState([])
  const [showCheckout, setShowCheckout] = useState(false)
  const [selectedProperty, setSelectedProperty] = useState(null)
  const [showReportGenerator, setShowReportGenerator] = useState(false)
  const [isGeneratingReport, setIsGeneratingReport] = useState(false)

  const handleDirectReportGeneration = () => {
    setIsGeneratingReport(true)
    
    setTimeout(() => {
      // Generate buyer report content
      const currentDate = new Date().toLocaleDateString()
      let content = `NAL PROPERTY PLATFORM - BUYER REPORT\n\n`
      content += `Generated: ${currentDate}\n\n`
      
      const purchases = JSON.parse(localStorage.getItem(`purchases_${user?.id}`) || '[]')
      const favorites = JSON.parse(localStorage.getItem('favorites') || '[]')
      
      content += `PURCHASE HISTORY (${purchases.length} transactions):\n\n`
      purchases.forEach((p, i) => {
        content += `${i+1}. ${p.property?.title || 'Property'}\n`
        content += `   Price: ${p.amount}\n`
        content += `   Date: ${new Date(p.purchaseDate).toLocaleDateString()}\n\n`
      })
      
      content += `FAVORITES: ${favorites.length} properties\n\n`
      content += `Report generated by NAL Property Platform`
      
      // Create HTML content for PDF
      const htmlContent = `
        <html>
          <head>
            <style>
              body { font-family: Arial, sans-serif; margin: 40px; }
              h1 { color: #1E3A8A; }
              .header { text-align: center; margin-bottom: 30px; }
              .content { line-height: 1.6; }
            </style>
          </head>
          <body>
            <div class="header">
              <h1>NAL Property Platform</h1>
              <h2>Buyer Report</h2>
            </div>
            <div class="content">
              <pre>${content}</pre>
            </div>
          </body>
        </html>
      `
      
      const element = document.createElement('a')
      const file = new Blob([htmlContent], {type: 'text/html'})
      element.href = URL.createObjectURL(file)
      element.download = `NAL-Buyer-Report-${new Date().toISOString().split('T')[0]}.html`
      document.body.appendChild(element)
      element.click()
      document.body.removeChild(element)
      
      setIsGeneratingReport(false)
    }, 2000)
  }

  const formatCurrency = (amount) => {
    if (amount >= 100) return `₹${(amount / 100).toFixed(1)} Cr`
    if (amount >= 1) return `₹${amount.toFixed(1)} L`
    return `₹${(amount * 100).toFixed(0)}`
  }

  useEffect(() => {
    // Load user data from localStorage
    const userViews = JSON.parse(localStorage.getItem(`recentViews_${user?.id}`) || '[]')
    const userPurchases = JSON.parse(localStorage.getItem(`purchases_${user?.id}`) || '[]')
    
    setRecentViews(userViews)
    
    // Add mock purchases if none exist
    if (userPurchases.length === 0) {
      const mockPurchases = [
        {
          id: 1,
          propertyId: 15,
          property: {
            title: '3BHK Luxury Condo',
            location: 'Bellandur, Bangalore',
            image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&h=300&fit=crop'
          },
          purchaseDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
          amount: '₹2.6 Cr',
          status: 'completed'
        },
        {
          id: 2,
          propertyId: 8,
          property: {
            title: '2BHK Garden View',
            location: 'HSR Layout, Bangalore',
            image: 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/736414796.jpg?k=3afde184481bd835cf71b2ba9ccbd83a3e31031a382cdd18ddc6f1814b64bfd4&o=&hp=1'
          },
          purchaseDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
          amount: '₹28,000/month',
          status: 'completed'
        }
      ]
      setPurchases(mockPurchases)
      localStorage.setItem(`purchases_${user?.id}`, JSON.stringify(mockPurchases))
    } else {
      setPurchases(userPurchases)
    }
  }, [user])

  const handleBuyProperty = (property) => {
    setSelectedProperty(property)
    setShowCheckout(true)
  }

  const handlePurchaseSuccess = () => {
    // Simulate purchase
    const purchase = {
      id: Date.now(),
      propertyId: selectedProperty.id,
      property: selectedProperty,
      purchaseDate: new Date().toISOString(),
      amount: selectedProperty.price,
      status: 'completed'
    }
    
    const updatedPurchases = [...purchases, purchase]
    setPurchases(updatedPurchases)
    localStorage.setItem(`purchases_${user?.id}`, JSON.stringify(updatedPurchases))
    
    setShowCheckout(false)
    setSelectedProperty(null)
  }

  const mockProperties = [
    {
      id: 1,
      title: '3BHK Luxury Apartment',
      location: 'Koramangala, Bangalore',
      price: '₹1.8 Cr',
      image: 'https://imagecdn.99acres.com/media1/32690/10/653810107M-1759080334729.jpg',
      type: 'sale',
      riblScore: 'A+',
      urgentSale: true
    },
    {
      id: 2,
      title: '2BHK Modern Flat',
      location: 'Indiranagar, Bangalore',
      price: '₹1.2 Cr',
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=400&h=300&fit=crop',
      type: 'sale',
      riblScore: 'A'
    },
    {
      id: 3,
      title: '4BHK Villa',
      location: 'HSR Layout, Bangalore',
      price: '₹2.8 Cr',
      image: 'https://th.bing.com/th/id/OIP.DCE_Nl83XmL1WHvbnMojzgHaFW?w=255&h=184&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3',
      type: 'sale',
      riblScore: 'A+',
      urgentSale: true
    }
  ]

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mb-8">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Buyer Dashboard</h1>
              <p className="text-gray-600">Track your property interests and purchases</p>
            </div>
            <button
              onClick={handleDirectReportGeneration}
              disabled={isGeneratingReport}
              className="bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white px-6 py-3 rounded-lg font-medium flex items-center gap-2 shadow-sm transition-colors"
            >
              {isGeneratingReport ? (
                <>
                  <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                  Generating...
                </>
              ) : (
                <>
                  <FileText className="w-5 h-5" />
                  Generate Report
                </>
              )}
            </button>
          </div>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Favorites</p>
                <p className="text-2xl font-bold text-gray-900">{favorites.length || 7}</p>
              </div>
              <Heart className="w-8 h-8 text-red-500" />
            </div>
          </div>

          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Recent Views</p>
                <p className="text-2xl font-bold text-gray-900">{recentViews.length || 12}</p>
              </div>
              <Eye className="w-8 h-8 text-blue-600" />
            </div>
          </div>

          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Purchases</p>
                <p className="text-2xl font-bold text-gray-900">{purchases.length || 2}</p>
              </div>
              <ShoppingCart className="w-8 h-8 text-green-600" />
            </div>
          </div>

          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Total Spent</p>
                <p className="text-2xl font-bold text-gray-900">
                  {purchases.length > 0 ? formatCurrency(purchases.reduce((sum, p) => {
                    const cleanAmount = p.amount.replace(/[₹,\s]/g, '')
                    if (cleanAmount.includes('Cr')) {
                      return sum + parseFloat(cleanAmount.replace('Cr', '')) * 100
                    } else if (cleanAmount.includes('L')) {
                      return sum + parseFloat(cleanAmount.replace('L', ''))
                    }
                    return sum + parseFloat(cleanAmount) / 100000
                  }, 0)) : '₹2.4 Cr'}
                </p>
              </div>
              <CreditCard className="w-8 h-8 text-purple-600" />
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Available Properties */}
          <div className="bg-white rounded-lg shadow-sm border border-gray-200">
            <div className="p-6 border-b border-gray-200">
              <h2 className="text-xl font-semibold text-gray-900">Available Properties</h2>
            </div>
            <div className="p-6 space-y-4">
              {mockProperties.map((property) => (
                <div key={property.id} className="border border-gray-200 rounded-lg p-4">
                  <div className="flex items-center gap-4">
                    <img
                      src={property.image}
                      alt={property.title}
                      className="w-16 h-16 rounded-lg object-cover"
                    />
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        <h3 className="font-medium text-gray-900">{property.title}</h3>
                        {property.urgentSale && (
                          <span className="bg-red-100 text-red-700 px-2 py-1 rounded-full text-xs font-medium">
                            Urgent Sale
                          </span>
                        )}
                      </div>
                      <div className="flex items-center gap-1 text-sm text-gray-500 mb-1">
                        <MapPin className="w-3 h-3" />
                        {property.location}
                      </div>
                      <div className="flex items-center justify-between">
                        <p className={`font-semibold ${property.urgentSale ? 'text-red-600' : 'text-primary-600'}`}>{property.price}</p>
                        <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                          property.riblScore === 'A+' ? 'bg-green-100 text-green-800' :
                          property.riblScore === 'A' ? 'bg-blue-100 text-blue-800' :
                          'bg-yellow-100 text-yellow-800'
                        }`}>
                          RIBL: {property.riblScore}
                        </span>
                      </div>
                    </div>
                    <button
                      onClick={() => handleBuyProperty(property)}
                      className="bg-primary-600 hover:bg-primary-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 shadow-sm"
                    >
                      <ShoppingCart className="w-4 h-4" />
                      Buy Now
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Recent Purchases */}
          <div className="bg-white rounded-lg shadow-sm border border-gray-200">
            <div className="p-6 border-b border-gray-200">
              <h2 className="text-xl font-semibold text-gray-900">Recent Purchases</h2>
            </div>
            <div className="p-6">
              {purchases.length === 0 ? (
                <div className="text-center py-8">
                  <ShoppingCart className="w-12 h-12 text-gray-300 mx-auto mb-4" />
                  <p className="text-gray-500">No purchases yet</p>
                </div>
              ) : (
                <div className="space-y-4">
                  {purchases.map((purchase) => (
                    <div key={purchase.id} className="border border-gray-200 rounded-lg p-4">
                      <div className="flex items-center gap-4">
                        <img
                          src={purchase.property.image}
                          alt={purchase.property.title}
                          className="w-12 h-12 rounded-lg object-cover"
                        />
                        <div className="flex-1">
                          <h3 className="font-medium text-gray-900">{purchase.property.title}</h3>
                          <p className="text-sm text-gray-500">
                            Purchased on {new Date(purchase.purchaseDate).toLocaleDateString()}
                          </p>
                          <p className="font-semibold text-green-600">{purchase.amount}</p>
                        </div>
                        <span className="px-2 py-1 text-xs font-medium rounded-full bg-green-100 text-green-800">
                          Completed
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Payment Gateway */}
        {showCheckout && selectedProperty && (
          <PaymentGateway
            property={selectedProperty}
            onClose={() => setShowCheckout(false)}
            onSuccess={handlePurchaseSuccess}
          />
        )}

        {/* Loading Overlay */}
        {isGeneratingReport && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
            <div className="bg-white rounded-lg p-8 max-w-md w-full mx-4 text-center">
              <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-blue-600 mx-auto mb-4"></div>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">Generating Report...</h3>
              <p className="text-gray-600">Compiling your purchase history and data</p>
            </div>
          </div>
        )}

        {/* Report Generator */}
        {showReportGenerator && (
          <ReportGenerator
            userType="buyer"
            onClose={() => setShowReportGenerator(false)}
          />
        )}

        {/* Quick Actions */}
        <div className="mt-8 bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">Quick Actions</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Link
              to="/urgent-sale-value"
              className="flex items-center gap-3 p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
            >
              <Zap className="w-6 h-6 text-orange-600" />
              <div>
                <h3 className="font-medium text-gray-900">Urgent Sale Value</h3>
                <p className="text-sm text-gray-500">Get property valuations</p>
              </div>
            </Link>

            <button 
              onClick={() => setShowReportGenerator(true)}
              className="flex items-center gap-3 p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
            >
              <FileText className="w-6 h-6 text-blue-600" />
              <div>
                <h3 className="font-medium text-gray-900">Purchase Reports</h3>
                <p className="text-sm text-gray-500">Download purchase history</p>
              </div>
            </button>

            <Link
              to="/properties"
              className="flex items-center gap-3 p-4 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
            >
              <Eye className="w-6 h-6 text-green-600" />
              <div>
                <h3 className="font-medium text-gray-900">Browse More</h3>
                <p className="text-sm text-gray-500">Explore properties</p>
              </div>
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}

export default BuyerDashboard