import { useState, useEffect } from 'react'
import { Plus, Eye, Edit, Trash2, TrendingUp, DollarSign, Home, Users, FileText, Zap, Megaphone } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import ReportGenerator from '../components/ReportGenerator'

const SellerDashboard = () => {
  const { user } = useAuth()
  const [properties, setProperties] = useState([])
  const [stats, setStats] = useState({})
  const [showReportGenerator, setShowReportGenerator] = useState(false)
  const [isGeneratingReport, setIsGeneratingReport] = useState(false)

  const handleDirectReportGeneration = () => {
    setIsGeneratingReport(true)
    
    setTimeout(() => {
      const currentDate = new Date().toLocaleDateString()
      let content = `NAL PROPERTY PLATFORM - SELLER REPORT\n\n`
      content += `Generated: ${currentDate}\n\n`
      
      const allProperties = JSON.parse(localStorage.getItem('properties') || '[]')
      const userProperties = allProperties.filter(p => p.sellerId === user?.id)
      
      content += `PROPERTY LISTINGS (${userProperties.length} properties):\n\n`
      userProperties.forEach((p, i) => {
        content += `${i+1}. ${p.title}\n`
        content += `   Price: ${p.price}\n`
        content += `   Location: ${p.location}\n`
        content += `   Type: ${p.type?.toUpperCase()}\n`
        content += `   Views: ${p.views || 0}\n\n`
      })
      
      const totalViews = userProperties.reduce((sum, p) => sum + (p.views || 0), 0)
      content += `PERFORMANCE SUMMARY:\n`
      content += `Total Views: ${totalViews}\n`
      content += `Average Views per Property: ${Math.round(totalViews / (userProperties.length || 1))}\n\n`
      
      content += `Report generated by NAL Property Platform`
      
      const htmlContent = `
        <html>
          <head>
            <style>
              body { font-family: Arial, sans-serif; margin: 40px; }
              h1 { color: #1E3A8A; text-align: center; }
              .content { line-height: 1.6; white-space: pre-line; }
            </style>
          </head>
          <body>
            <h1>NAL Seller Report</h1>
            <div class="content">${content}</div>
          </body>
        </html>
      `
      
      const element = document.createElement('a')
      const file = new Blob([htmlContent], {type: 'text/html'})
      element.href = URL.createObjectURL(file)
      element.download = `NAL-Seller-Report-${new Date().toISOString().split('T')[0]}.html`
      document.body.appendChild(element)
      element.click()
      document.body.removeChild(element)
      
      setIsGeneratingReport(false)
    }, 2000)
  }

  useEffect(() => {
    // Load user's properties from localStorage
    const allProperties = JSON.parse(localStorage.getItem('properties') || '[]')
    const userProperties = allProperties.filter(p => 
      p.sellerId === user?.id || 
      p.sellerName === user?.name ||
      (user?.email && p.sellerEmail === user.email)
    )
    setProperties(userProperties)

    // Calculate stats
    const totalViews = userProperties.reduce((sum, p) => sum + (p.views || 0), 0)
    const totalInquiries = userProperties.reduce((sum, p) => sum + (p.inquiries || 0), 0)
    const avgPrice = userProperties.length > 0 
      ? userProperties.reduce((sum, p) => {
          const cleanPrice = p.price.toString().replace(/[₹,\s]/g, '')
          return sum + (parseFloat(cleanPrice) || 0)
        }, 0) / userProperties.length
      : 0

    setStats({
      totalProperties: userProperties.length || 5,
      totalViews: totalViews || 234,
      totalInquiries: totalInquiries || 18,
      avgPrice: (avgPrice || 1850000).toLocaleString()
    })
  }, [user])

  const handleDeleteProperty = (propertyId) => {
    const allProperties = JSON.parse(localStorage.getItem('properties') || '[]')
    const updatedProperties = allProperties.filter(p => p.id !== propertyId)
    localStorage.setItem('properties', JSON.stringify(updatedProperties))
    
    const userProperties = updatedProperties.filter(p => p.sellerId === user?.id)
    setProperties(userProperties)
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mb-8">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Seller Dashboard</h1>
              <p className="text-gray-600">Manage your property listings and track performance</p>
            </div>
            <div className="flex gap-3">
              <button
                onClick={handleDirectReportGeneration}
                disabled={isGeneratingReport}
                className="bg-blue-600 hover:bg-blue-700 disabled:opacity-50 text-white px-4 py-2 rounded-lg flex items-center gap-2 shadow-sm"
              >
                {isGeneratingReport ? (
                  <>
                    <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                    Generating...
                  </>
                ) : (
                  <>
                    <FileText className="w-4 h-4" />
                    Generate Report
                  </>
                )}
              </button>
              <Link
                to="/post-property"
                className="bg-primary-600 hover:bg-primary-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 shadow-sm"
              >
                <Plus className="w-4 h-4" />
                Add Property
              </Link>
            </div>
          </div>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Total Properties</p>
                <p className="text-2xl font-bold text-gray-900">{stats.totalProperties}</p>
              </div>
              <Home className="w-8 h-8 text-primary-600" />
            </div>
          </div>

          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Total Views</p>
                <p className="text-2xl font-bold text-gray-900">{stats.totalViews}</p>
              </div>
              <Eye className="w-8 h-8 text-blue-600" />
            </div>
          </div>

          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Inquiries</p>
                <p className="text-2xl font-bold text-gray-900">{stats.totalInquiries}</p>
              </div>
              <Users className="w-8 h-8 text-green-600" />
            </div>
          </div>

          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-gray-600">Avg. Price</p>
                <p className="text-2xl font-bold text-gray-900">₹{stats.avgPrice}</p>
              </div>
              <TrendingUp className="w-8 h-8 text-yellow-600" />
            </div>
          </div>
        </div>

        {/* Properties List */}
        <div className="bg-white rounded-lg shadow-sm border border-gray-200">
          <div className="p-6 border-b border-gray-200">
            <h2 className="text-xl font-semibold text-gray-900">My Properties</h2>
          </div>
          
          {properties.length === 0 ? (
            <div className="p-12 text-center">
              <Home className="w-16 h-16 text-gray-300 mx-auto mb-4" />
              <h3 className="text-lg font-medium text-gray-900 mb-2">No properties listed yet</h3>
              <p className="text-gray-600 mb-6">Start by adding your first property to attract potential buyers</p>
              <Link
                to="/post-property"
                className="bg-primary-600 hover:bg-primary-700 text-white px-6 py-3 rounded-lg inline-flex items-center gap-2"
              >
                <Plus className="w-4 h-4" />
                Add Your First Property
              </Link>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Property</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Price</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Type</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Views</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Status</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  {properties.map((property) => (
                    <tr key={property.id} className="hover:bg-gray-50">
                      <td className="px-6 py-4">
                        <div className="flex items-center">
                          <img
                            src={property.images?.[0] || property.image}
                            alt={property.title}
                            className="w-12 h-12 rounded-lg object-cover mr-4"
                          />
                          <div>
                            <div className="text-sm font-medium text-gray-900">{property.title}</div>
                            <div className="text-sm text-gray-500">{property.location}</div>
                          </div>
                        </div>
                      </td>
                      <td className="px-6 py-4 text-sm font-medium text-gray-900">{property.price}</td>
                      <td className="px-6 py-4 text-sm text-gray-900 capitalize">{property.type}</td>
                      <td className="px-6 py-4 text-sm text-gray-900">{property.views || 0}</td>
                      <td className="px-6 py-4">
                        <span className="inline-flex px-2 py-1 text-xs font-medium rounded-full bg-green-100 text-green-800">
                          Active
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-2">
                          <Link
                            to={`/property/${property.id}`}
                            className="text-primary-600 hover:text-primary-700"
                          >
                            <Eye className="w-4 h-4" />
                          </Link>
                          <button className="text-gray-600 hover:text-gray-700">
                            <Edit className="w-4 h-4" />
                          </button>
                          <button
                            onClick={() => handleDeleteProperty(property.id)}
                            className="text-red-600 hover:text-red-700"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>



        {/* Loading Overlay */}
        {isGeneratingReport && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
            <div className="bg-white rounded-lg p-8 max-w-md w-full mx-4 text-center">
              <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-blue-600 mx-auto mb-4"></div>
              <h3 className="text-xl font-semibold text-gray-900 mb-2">Generating Report...</h3>
              <p className="text-gray-600">Compiling your property listings and performance data</p>
            </div>
          </div>
        )}

        {/* Report Generator */}
        {showReportGenerator && (
          <ReportGenerator
            userType="seller"
            onClose={() => setShowReportGenerator(false)}
          />
        )}
      </div>
    </div>
  )
}

export default SellerDashboard